export const scenarioTemplates: Record<string, any> = {
    "SN001": {
        "invoiceType": "Sale Invoice",
        "invoiceDate": "2025-05-10",
        "sellerBusinessName": "XYZ",
        "sellerProvince": "Sindh",
        "sellerNTNCNIC": "0000000",
        "sellerAddress": "Karachi",
        "buyerNTNCNIC": "2046004",
        "buyerBusinessName": "ABC",
        "buyerProvince": "Sindh",
        "buyerAddress": "Karachi",
        "invoiceRefNo": "",
        "scenarioId": "SN001",
        "buyerRegistrationType": "Registered",
        "items": [
            {
                "hsCode": "0101.2100",
                "productDescription": "test",
                "rate": "18%",
                "uoM": "Numbers, pieces, units",
                "quantity": 400,
                "totalValues": 0,
                "valueSalesExcludingST": 1000,
                "fixedNotifiedValueOrRetailPrice": 0.0,
                "salesTaxApplicable": 180,
                "salesTaxWithheldAtSource": 0,
                "extraTax": "",
                "furtherTax": 0,
                "sroScheduleNo": "",
                "fedPayable": 0,
                "discount": 0,
                "saleType": "Goods at standard rate (default)",
                "sroItemSerialNo": ""
            }
        ]
    },
    "SN002": {
        "invoiceType": "Sale Invoice",
        "invoiceDate": "2025-05-10",
        "sellerBusinessName": "XYZ",
        "sellerProvince": "Sindh",
        "sellerNTNCNIC": "0000000",
        "sellerAddress": "Karachi",
        "buyerNTNCNIC": "1234567",
        "buyerBusinessName": "ABC",
        "buyerProvince": "Sindh",
        "buyerAddress": "Karachi",
        "invoiceRefNo": "",
        "scenarioId": "SN002",
        "buyerRegistrationType": "Unregistered",
        "items": [
            {
                "hsCode": "0101.2100",
                "productDescription": "test",
                "rate": "18%",
                "uoM": "Numbers, pieces, units",
                "quantity": 400,
                "totalValues": 0,
                "valueSalesExcludingST": 1000,
                "fixedNotifiedValueOrRetailPrice": 0.0,
                "salesTaxApplicable": 180,
                "salesTaxWithheldAtSource": 0,
                "extraTax": "",
                "furtherTax": 0,
                "sroScheduleNo": "",
                "fedPayable": 0,
                "discount": 0,
                "saleType": "Goods at standard rate (default)",
                "sroItemSerialNo": ""
            }
        ]
    },
    "SN003": {
        "invoiceType": "Sale Invoice",
        "invoiceDate": "2025-04-21",
        "sellerBusinessName": "Company 7",
        "sellerNTNCNIC": "0000000",
        "sellerProvince": "Sindh",
        "buyerNTNCNIC": "0000000",
        "buyerBusinessName": "ABC",
        "buyerProvince": "Sindh",
        "buyerAddress": "Karachi",
        "sellerAddress": "Karachi",
        "invoiceRefNo": "0",
        "scenarioId": "SN003",
        "buyerRegistrationType": "Unregistered",
        "items": [
            {
                "hsCode": "7214.1010",
                "productDescription": "",
                "rate": "18%",
                "uoM": "MT",
                "quantity": 1,
                "totalValues": 0,
                "valueSalesExcludingST": 205000.0,
                "fixedNotifiedValueOrRetailPrice": 0.0,
                "salesTaxApplicable": 36900,
                "salesTaxWithheldAtSource": 0,
                "extraTax": 0,
                "furtherTax": 0,
                "sroScheduleNo": "",
                "fedPayable": 0,
                "discount": 0,
                "saleType": "Steel melting and re-rolling",
                "sroItemSerialNo": ""
            }
        ]
    },
    "SN004": {
        "invoiceType": "Sale Invoice",
        "invoiceDate": "2025-05-26",
        "sellerNTNCNIC": "0000000",
        "sellerBusinessName": "XYZ",
        "sellerAddress": "Karachi",
        "sellerProvince": "Sindh",
        "buyerNTNCNIC": "0000000",
        "buyerBusinessName": "ABC",
        "buyerProvince": "Sindh",
        "buyerAddress": "Karachi",
        "scenarioId": "SN004",
        "invoiceRefNo": "",
        "buyerRegistrationType": "Unregistered",
        "items": [
            {
                "hsCode": "7202.1100",
                "productDescription": "Test",
                "rate": "18%",
                "uoM": "KG",
                "quantity": 1,
                "totalValues": 0,
                "valueSalesExcludingST": 175000,
                "salesTaxApplicable": 31500,
                "fixedNotifiedValueOrRetailPrice": 0,
                "salesTaxWithheldAtSource": 0,
                "extraTax": 0,
                "furtherTax": 0,
                "sroScheduleNo": "",
                "fedPayable": 0,
                "discount": 0,
                "saleType": "Ship breaking",
                "sroItemSerialNo": ""
            }
        ]
    },
    "SN005": {
        "invoiceType": "Sale Invoice",
        "invoiceDate": "2025-06-30",
        "sellerNTNCNIC": "0000000",
        "sellerBusinessName": "B2",
        "sellerAddress": "Karachi",
        "sellerProvince": "Sindh",
        "buyerNTNCNIC": "0000000",
        "buyerBusinessName": "ABC",
        "buyerProvince": "Sindh",
        "buyerAddress": "Karachi",
        "invoiceRefNo": "",
        "scenarioId": "SN005",
        "buyerRegistrationType": "Unregistered",
        "items": [
            {
                "hsCode": "0102.2930",
                "productDescription": "product Description41",
                "rate": "1%",
                "uoM": "Numbers, pieces, units",
                "quantity": 1.0,
                "totalValues": 0.00,
                "valueSalesExcludingST": 1000.00,
                "fixedNotifiedValueOrRetailPrice": 0.00,
                "salesTaxApplicable": 10,
                "salesTaxWithheldAtSource": 50.23,
                "extraTax": "",
                "furtherTax": 120.00,
                "sroScheduleNo": "EIGHTH SCHEDULE Table 1",
                "fedPayable": 50.36,
                "discount": 56.36,
                "saleType": "Goods at Reduced Rate",
                "sroItemSerialNo": "82"
            }
        ]
    },
    "SN006": {
        "invoiceType": "Sale Invoice",
        "invoiceDate": "2025-07-01",
        "sellerBusinessName": "XYZ",
        "sellerNTNCNIC": "0000000",
        "sellerProvince": "Sindh",
        "sellerAddress": "Karachi",
        "buyerNTNCNIC": "2046004",
        "buyerBusinessName": "ABC",
        "buyerProvince": "Sindh",
        "buyerAddress": "Karachi",
        "invoiceRefNo": "SI-20250515-001",
        "scenarioId": "SN006",
        "buyerRegistrationType": "Registered",
        "items": [
            {
                "hsCode": "0102.2930",
                "productDescription": "product Description41",
                "rate": "Exempt",
                "uoM": "Numbers, pieces, units",
                "quantity": 1.0,
                "totalValues": 0.00,
                "valueSalesExcludingST": 10,
                "fixedNotifiedValueOrRetailPrice": 0.00,
                "salesTaxApplicable": 0,
                "salesTaxWithheldAtSource": 50.23,
                "extraTax": "",
                "furtherTax": 120.00,
                "sroScheduleNo": "6th Schd Table I",
                "fedPayable": 50.36,
                "discount": 56.36,
                "saleType": "Exempt goods",
                "sroItemSerialNo": "100"
            }
        ]
    },
    "SN007": {
        "invoiceType": "Sale Invoice",
        "invoiceDate": "2025-04-21",
        "sellerBusinessName": "Company 7",
        "sellerNTNCNIC": "0000000",
        "sellerProvince": "Sindh",
        "buyerNTNCNIC": "0000000",
        "buyerBusinessName": "ABC",
        "buyerProvince": "Sindh",
        "buyerAddress": "Karachi",
        "sellerAddress": "Karachi",
        "scenarioId": "SN007",
        "buyerRegistrationType": "Unregistered",
        "invoiceRefNo": "0",
        "items": [
            {
                "hsCode": "0101.2100",
                "productDescription": "test",
                "rate": "0%",
                "uoM": "Numbers, pieces, units",
                "quantity": 100,
                "totalValues": 0,
                "valueSalesExcludingST": 100,
                "salesTaxApplicable": 0,
                "salesTaxWithheldAtSource": 0,
                "extraTax": 0,
                "furtherTax": 0,
                "sroScheduleNo": "327(I)/2008",
                "fixedNotifiedValueOrRetailPrice": 0.00,
                "fedPayable": 0,
                "discount": 0,
                "saleType": "Goods at zero-rate",
                "sroItemSerialNo": "1"
            }
        ]
    },
    "SN008": {
        invoiceType: "Sale Invoice",
        invoiceDate: "2025-12-09",
        invoiceRefNo: "",
        buyerNTNCNIC: "0000000",
        buyerBusinessName: "FERTILIZER MANUFACTURERS NEW",
        buyerProvince: "Sindh",
        buyerAddress: "Karachi",
        buyerRegistrationType: "Unregistered",
        items: [{
            hsCode: "0909.3200",
            productDescription: "Tea bags",
            rate: "18%",
            uoM: "KG",
            quantity: 1,
            totalValues: 307.37,
            valueSalesExcludingST: 212.00,
            fixedNotifiedValueOrRetailPrice: 212.00,
            salesTaxApplicable: 38.16,
            salesTaxWithheldAtSource: 0.00,
            extraTax: 15.00,
            furtherTax: 42.37,
            fedPayable: 50.00,
            discount: 0.00,
            saleType: "3rd Schedule Goods",
            sroItemSerialNo: "",
            sroScheduleNo: ""
        }]
    },
    "SN009": {
        "invoiceType": "Sale Invoice",
        "invoiceDate": "2025-05-15",
        "sellerNTNCNIC": "0000000",
        "sellerBusinessName": "XYZ",
        "sellerProvince": "Sindh",
        "sellerAddress": "Karachi",
        "buyerNTNCNIC": "2046004",
        "buyerBusinessName": "ABC",
        "buyerProvince": "Sindh",
        "buyerAddress": "Karachi",
        "invoiceRefNo": "",
        "scenarioId": "SN009",
        "buyerRegistrationType": "Registered",
        "items": [
            {
                "hsCode": "0101.2100",
                "productDescription": "test",
                "rate": "18%",
                "uoM": "Numbers, pieces, units",
                "quantity": 0,
                "totalValues": 2500,
                "valueSalesExcludingST": 2500,
                "fixedNotifiedValueOrRetailPrice": 0.00,
                "salesTaxApplicable": 450,
                "salesTaxWithheldAtSource": 0,
                "extraTax": 0,
                "furtherTax": 0,
                "sroScheduleNo": "",
                "fedPayable": 0,
                "discount": 0,
                "saleType": "Cotton ginners",
                "sroItemSerialNo": ""
            }
        ]
    },
    "SN010": {
        "invoiceType": "Sale Invoice",
        "invoiceDate": "2025-05-15",
        "sellerBusinessName": "XYZ",
        "sellerNTNCNIC": "0000000",
        "sellerProvince": "Sindh",
        "sellerAddress": "Karachi",
        "buyerNTNCNIC": "0000000",
        "buyerBusinessName": "ABC",
        "buyerProvince": "Sindh",
        "buyerAddress": "Karachi",
        "invoiceRefNo": "",
        "scenarioId": "SN010",
        "buyerRegistrationType": "Unregistered",
        "items": [
            {
                "hsCode": "0101.2100",
                "productDescription": "test",
                "rate": "17%",
                "uoM": "Numbers, pieces, units",
                "quantity": 1000,
                "totalValues": 0,
                "valueSalesExcludingST": 100,
                "fixedNotifiedValueOrRetailPrice": 0.00,
                "salesTaxApplicable": 17,
                "salesTaxWithheldAtSource": 0,
                "extraTax": 0,
                "furtherTax": 0,
                "sroScheduleNo": "",
                "fedPayable": 0,
                "discount": 0,
                "saleType": "Telecommunication services",
                "sroItemSerialNo": ""
            }
        ]
    },
    "SN011": {
        "invoiceType": "Sale Invoice",
        "invoiceDate": "2025-05-26",
        "sellerNTNCNIC": "0000000",
        "sellerBusinessName": "XYZ",
        "sellerAddress": "Karachi",
        "sellerProvince": "Sindh",
        "buyerNTNCNIC": "0000000",
        "buyerBusinessName": "ABC",
        "buyerProvince": "Sindh",
        "buyerAddress": "Karachi",
        "invoiceRefNo": "",
        "scenarioId": "SN011",
        "buyerRegistrationType": "Unregistered",
        "items": [
            {
                "hsCode": "7214.9990",
                "productDescription": "Test",
                "rate": "18%",
                "uoM": "MT",
                "quantity": 1,
                "totalValues": 0,
                "valueSalesExcludingST": 205000,
                "salesTaxApplicable": 36900,
                "fixedNotifiedValueOrRetailPrice": 0,
                "salesTaxWithheldAtSource": 0,
                "extraTax": 0,
                "furtherTax": 0,
                "sroScheduleNo": "",
                "fedPayable": 0,
                "discount": 0,
                "saleType": "Toll Manufacturing",
                "sroItemSerialNo": ""
            }
        ]
    },
    "SN012": {
        "invoiceType": "Sale Invoice",
        "invoiceDate": "2025-05-15",
        "sellerNTNCNIC": "0000000",
        "sellerBusinessName": "XYZ",
        "sellerProvince": "Sindh",
        "sellerAddress": "Karachi",
        "buyerNTNCNIC": "0000000",
        "buyerBusinessName": "ABC",
        "buyerProvince": "Sindh",
        "buyerAddress": "Karachi",
        "invoiceRefNo": "",
        "scenarioId": "SN012",
        "buyerRegistrationType": "Unregistered",
        "items": [
            {
                "hsCode": "0101.2100",
                "productDescription": "TEST",
                "rate": "1.43%",
                "uoM": "Numbers, pieces, units",
                "quantity": 123,
                "totalValues": 132,
                "valueSalesExcludingST": 100,
                "fixedNotifiedValueOrRetailPrice": 0.00,
                "salesTaxApplicable": 1.43,
                "salesTaxWithheldAtSource": 2,
                "extraTax": 0,
                "furtherTax": 0,
                "sroScheduleNo": "1450(I)/2021",
                "fedPayable": 0,
                "discount": 0,
                "saleType": "Petroleum Products",
                "sroItemSerialNo": "4"
            }
        ]
    },
    "SN013": {
        "invoiceType": "Sale Invoice",
        "invoiceDate": "2025-05-15",
        "sellerNTNCNIC": "0000000",
        "sellerBusinessName": "XYZ",
        "sellerProvince": "Sindh",
        "sellerAddress": "Karachi",
        "buyerNTNCNIC": "0000000",
        "buyerBusinessName": "ABC",
        "buyerProvince": "Sindh",
        "buyerAddress": "Karachi",
        "invoiceRefNo": "",
        "scenarioId": "SN013",
        "buyerRegistrationType": "Unregistered",
        "items": [
            {
                "hsCode": "0101.2100",
                "productDescription": "TEST",
                "rate": "5%",
                "uoM": "Numbers, pieces, units",
                "quantity": 123,
                "totalValues": 212,
                "valueSalesExcludingST": 1000,
                "fixedNotifiedValueOrRetailPrice": 0.00,
                "salesTaxApplicable": 50,
                "salesTaxWithheldAtSource": 11,
                "extraTax": 0,
                "furtherTax": 0,
                "sroScheduleNo": "1450(I)/2021",
                "fedPayable": 0,
                "discount": 0,
                "saleType": "Electricity Supply to Retailers",
                "sroItemSerialNo": "4"
            }
        ]
    },
    "SN014": {
        "invoiceType": "Sale Invoice",
        "invoiceDate": "2025-05-15",
        "sellerNTNCNIC": "0000000",
        "sellerBusinessName": "XYZ",
        "sellerProvince": "Sindh",
        "sellerAddress": "Karachi",
        "buyerNTNCNIC": "0000000",
        "buyerBusinessName": "ABC",
        "buyerProvince": "Sindh",
        "buyerAddress": "Karachi",
        "invoiceRefNo": "",
        "scenarioId": "SN014",
        "buyerRegistrationType": "Unregistered",
        "items": [
            {
                "hsCode": "0101.2100",
                "productDescription": "TEST",
                "rate": "18%",
                "uoM": "Numbers, pieces, units",
                "quantity": 123,
                "totalValues": 0,
                "valueSalesExcludingST": 1000,
                "salesTaxApplicable": 180,
                "salesTaxWithheldAtSource": 0,
                "fixedNotifiedValueOrRetailPrice": 0,
                "extraTax": 0,
                "furtherTax": 0,
                "sroScheduleNo": "",
                "fedPayable": 0,
                "discount": 0,
                "saleType": "Gas to CNG stations",
                "sroItemSerialNo": ""
            }
        ]
    },
    "SN015": {
        "invoiceType": "Sale Invoice",
        "invoiceDate": "2025-05-15",
        "sellerBusinessName": "XYZ",
        "sellerNTNCNIC": "0000000",
        "sellerProvince": "Sindh",
        "sellerAddress": "Karachi",
        "buyerNTNCNIC": "0000000",
        "buyerBusinessName": "ABC",
        "buyerProvince": "Sindh",
        "buyerAddress": "Karachi",
        "invoiceRefNo": "",
        "scenarioId": "SN015",
        "buyerRegistrationType": "Unregistered",
        "items": [
            {
                "hsCode": "0101.2100",
                "productDescription": "TEST",
                "rate": "18%",
                "uoM": "Numbers, pieces, units",
                "quantity": 123,
                "totalValues": 0,
                "valueSalesExcludingST": 1234,
                "salesTaxApplicable": 222.12,
                "salesTaxWithheldAtSource": 0,
                "fixedNotifiedValueOrRetailPrice": 0,
                "extraTax": 0,
                "furtherTax": 0,
                "sroScheduleNo": "NINTH SCHEDULE",
                "fedPayable": 0,
                "discount": 0,
                "saleType": "Mobile Phones",
                "sroItemSerialNo": "1(A)"
            }
        ]
    },
    "SN016": {
        "invoiceType": "Sale Invoice",
        "invoiceDate": "2025-05-16",
        "sellerNTNCNIC": "0000000",
        "sellerBusinessName": "XYZ",
        "sellerProvince": "Sindh",
        "sellerAddress": "Karachi",
        "buyerNTNCNIC": "0000000",
        "buyerBusinessName": "ABC",
        "buyerProvince": "Sindh",
        "buyerAddress": "Karachi",
        "invoiceRefNo": "",
        "scenarioId": "SN016",
        "buyerRegistrationType": "Unregistered",
        "items": [
            {
                "hsCode": "0101.2100",
                "productDescription": "test",
                "rate": "5%",
                "uoM": "Numbers, pieces, units",
                "quantity": 1,
                "totalValues": 0,
                "valueSalesExcludingST": 100,
                "salesTaxApplicable": 5,
                "salesTaxWithheldAtSource": 0,
                "fixedNotifiedValueOrRetailPrice": 0,
                "extraTax": 0,
                "furtherTax": 0,
                "sroScheduleNo": "",
                "fedPayable": 0,
                "discount": 0,
                "saleType": "Processing/Conversion of Goods",
                "sroItemSerialNo": ""
            }
        ]
    },
    "SN017": {
        "invoiceType": "Sale Invoice",
        "invoiceDate": "2025-05-10",
        "sellerNTNCNIC": "0000000",
        "sellerBusinessName": "XYZ",
        "sellerProvince": "Sindh",
        "sellerAddress": "Karachi",
        "buyerNTNCNIC": "0000000",
        "buyerBusinessName": "ABC",
        "buyerProvince": "Sindh",
        "buyerAddress": "Karachi",
        "invoiceRefNo": "",
        "scenarioId": "SN017",
        "buyerRegistrationType": "Unregistered",
        "items": [
            {
                "hsCode": "0101.2100",
                "productDescription": "TEST",
                "rate": "8%",
                "uoM": "Numbers, pieces, units",
                "quantity": 1,
                "valueSalesExcludingST": 100,
                "fixedNotifiedValueOrRetailPrice": 0,
                "salesTaxApplicable": 8,
                "salesTaxWithheldAtSource": 0,
                "extraTax": 0,
                "furtherTax": 0,
                "fedPayable": 0,
                "discount": 0,
                "totalValues": 0,
                "saleType": "Goods (FED in ST Mode)",
                "sroScheduleNo": "",
                "sroItemSerialNo": ""
            }
        ]
    },
    "SN018": {
        "invoiceType": "Sale Invoice",
        "invoiceDate": "2025-06-14",
        "sellerNTNCNIC": "0000000",
        "sellerBusinessName": "XYZ",
        "sellerProvince": "Sindh",
        "sellerAddress": "Karachi",
        "buyerNTNCNIC": "0000000",
        "buyerBusinessName": "ABC",
        "buyerProvince": "Sindh",
        "buyerAddress": "Karachi",
        "invoiceRefNo": "",
        "scenarioId": "SN018",
        "buyerRegistrationType": "Unregistered",
        "items": [
            {
                "hsCode": "0101.2100",
                "productDescription": "TEST",
                "rate": "8%",
                "uoM": "Numbers, pieces, units",
                "quantity": 20,
                "totalValues": 0,
                "valueSalesExcludingST": 1000,
                "salesTaxApplicable": 80,
                "fixedNotifiedValueOrRetailPrice": 0,
                "salesTaxWithheldAtSource": 0,
                "extraTax": 0,
                "furtherTax": 0,
                "sroScheduleNo": "",
                "fedPayable": 0,
                "discount": 0,
                "saleType": "Services (FED in ST Mode)",
                "sroItemSerialNo": ""
            }
        ]
    },
    "SN019": {
        "invoiceType": "Sale Invoice",
        "invoiceDate": "2025-04-21",
        "sellerNTNCNIC": "0000000",
        "sellerBusinessName": "XYZ",
        "sellerProvince": "Sindh",
        "sellerAddress": "Karachi",
        "buyerNTNCNIC": "0000000",
        "buyerBusinessName": "ABC",
        "buyerProvince": "Sindh",
        "buyerAddress": "Karachi",
        "scenarioId": "SN019",
        "invoiceRefNo": "",
        "buyerRegistrationType": "Unregistered",
        "items": [
            {
                "hsCode": "0101.2900",
                "productDescription": "TEST",
                "rate": "5%",
                "uoM": "Numbers, pieces, units",
                "quantity": 1,
                "totalValues": 0,
                "valueSalesExcludingST": 100,
                "salesTaxApplicable": 5,
                "fixedNotifiedValueOrRetailPrice": 0,
                "salesTaxWithheldAtSource": 0,
                "extraTax": 0,
                "furtherTax": 0,
                "sroScheduleNo": "ICTO TABLE I",
                "fedPayable": 0,
                "discount": 0,
                "saleType": "Services",
                "sroItemSerialNo": "1(ii)(ii)(a)"
            }
        ]
    },
    "SN020": {
        "invoiceType": "Sale Invoice",
        "invoiceDate": "2025-04-21",
        "sellerNTNCNIC": "0000000",
        "sellerBusinessName": "XYZ",
        "sellerProvince": "Sindh",
        "sellerAddress": "Karachi",
        "buyerNTNCNIC": "0000000",
        "buyerBusinessName": "ABC",
        "buyerProvince": "Sindh",
        "buyerAddress": "Karachi",
        "scenarioId": "SN020",
        "invoiceRefNo": "",
        "buyerRegistrationType": "Unregistered",
        "items": [
            {
                "hsCode": "0101.2900",
                "productDescription": "TEST",
                "rate": "1%",
                "uoM": "Numbers, pieces, units",
                "quantity": 122,
                "totalValues": 0,
                "valueSalesExcludingST": 1000,
                "salesTaxApplicable": 10,
                "salesTaxWithheldAtSource": 0,
                "fixedNotifiedValueOrRetailPrice": 0,
                "extraTax": 0,
                "furtherTax": 0,
                "sroScheduleNo": "6th Schd Table III",
                "fedPayable": 0,
                "discount": 0,
                "saleType": "Electric Vehicle",
                "sroItemSerialNo": "20"
            }
        ]
    },
    "SN021": {
        "invoiceType": "Sale Invoice",
        "invoiceDate": "2025-04-21",
        "sellerNTNCNIC": "0000000",
        "sellerBusinessName": "XYZ",
        "sellerProvince": "Sindh",
        "sellerAddress": "Karachi",
        "buyerNTNCNIC": "0000000",
        "buyerBusinessName": "ABC",
        "buyerProvince": "Sindh",
        "buyerAddress": "Karachi",
        "scenarioId": "SN021",
        "invoiceRefNo": "",
        "buyerRegistrationType": "Unregistered",
        "items": [
            {
                "hsCode": "0101.2100",
                "productDescription": "TEST",
                "rate": "Rs.3",
                "uoM": "Numbers, pieces, units",
                "quantity": 1,
                "totalValues": 2503,
                "valueSalesExcludingST": 2500,
                "salesTaxApplicable": 3,
                "fixedNotifiedValueOrRetailPrice": 2500,
                "salesTaxWithheldAtSource": 0,
                "extraTax": 0,
                "furtherTax": 0,
                "sroScheduleNo": "",
                "fedPayable": 0,
                "discount": 0,
                "saleType": "Cement /Concrete Block",
                "sroItemSerialNo": ""
            }
        ]
    },
    "SN022": {
        "invoiceType": "Sale Invoice",
        "invoiceDate": "2025-04-21",
        "sellerNTNCNIC": "0000000",
        "sellerBusinessName": "XYZ",
        "sellerProvince": "Sindh",
        "sellerAddress": "Karachi",
        "buyerNTNCNIC": "0000000",
        "buyerBusinessName": "ABC",
        "buyerProvince": "Sindh",
        "buyerAddress": "Karachi",
        "scenarioId": "SN022",
        "invoiceRefNo": "",
        "buyerRegistrationType": "Unregistered",
        "items": [
            {
                "hsCode": "3104.2000",
                "productDescription": "TEST",
                "rate": "18% along with rupees 60 per kilogram",
                "uoM": "KG",
                "quantity": 1,
                "valueSalesExcludingST": 100,
                "fixedNotifiedValueOrRetailPrice": 60,
                "salesTaxApplicable": 78,
                "salesTaxWithheldAtSource": 0,
                "extraTax": 0,
                "furtherTax": 0,
                "sroScheduleNo": "EIGHTH SCHEDULE Table 1",
                "fedPayable": 0,
                "discount": 0,
                "totalValues": 0,
                "saleType": "Potassium Chlorate",
                "sroItemSerialNo": "56"
            }
        ]
    },
    "SN023": {
        "invoiceType": "Sale Invoice",
        "invoiceDate": "2025-04-21",
        "sellerNTNCNIC": "0000000",
        "sellerBusinessName": "XYZ",
        "sellerProvince": "Sindh",
        "sellerAddress": "Karachi",
        "buyerNTNCNIC": "0000000",
        "buyerBusinessName": "ABC",
        "buyerProvince": "Sindh",
        "buyerAddress": "Karachi",
        "scenarioId": "SN023",
        "invoiceRefNo": "",
        "buyerRegistrationType": "Unregistered",
        "items": [
            {
                "hsCode": "0101.2100",
                "productDescription": "TEST",
                "rate": "Rs.200",
                "uoM": "Numbers, pieces, units",
                "quantity": 1,
                "valueSalesExcludingST": 1000,
                "fixedNotifiedValueOrRetailPrice": 1000,
                "salesTaxApplicable": 200,
                "salesTaxWithheldAtSource": 0,
                "extraTax": 0,
                "furtherTax": 0,
                "sroScheduleNo": "581(1)/2024",
                "fedPayable": 0,
                "discount": 0,
                "totalValues": 0,
                "saleType": "CNG Sales",
                "sroItemSerialNo": "Region-I"
            }
        ]
    },
    "SN024": {
        "invoiceType": "Sale Invoice",
        "invoiceDate": "2025-04-21",
        "sellerNTNCNIC": "0000000",
        "sellerBusinessName": "XYZ",
        "sellerProvince": "Sindh",
        "sellerAddress": "Karachi",
        "buyerNTNCNIC": "0000000",
        "buyerBusinessName": "ABC",
        "buyerProvince": "Sindh",
        "buyerAddress": "Karachi",
        "scenarioId": "SN024",
        "invoiceRefNo": "",
        "buyerRegistrationType": "Unregistered",
        "items": [
            {
                "hsCode": "0101.2100",
                "productDescription": "TEST",
                "rate": "25%",
                "uoM": "Numbers, pieces, units",
                "quantity": 123,
                "valueSalesExcludingST": 1000,
                "fixedNotifiedValueOrRetailPrice": 0,
                "salesTaxApplicable": 250,
                "salesTaxWithheldAtSource": 0,
                "extraTax": 0,
                "furtherTax": 0,
                "sroScheduleNo": "297(I)/2023-Table-I",
                "fedPayable": 0,
                "discount": 0,
                "totalValues": 0,
                "saleType": "Goods as per SRO.297(|)/2023",
                "sroItemSerialNo": "12"
            }
        ]
    },
    "SN025": {
        "invoiceType": "Sale Invoice",
        "invoiceDate": "2025-05-16",
        "sellerNTNCNIC": "0000000",
        "sellerBusinessName": "XYZ",
        "sellerAddress": "Karachi",
        "sellerProvince": "Sindh",
        "buyerNTNCNIC": "0000000",
        "buyerBusinessName": "ABC",
        "buyerProvince": "Sindh",
        "buyerAddress": "Karachi",
        "scenarioId": "SN025",
        "invoiceRefNo": "",
        "buyerRegistrationType": "Unregistered",
        "items": [
            {
                "hsCode": "0101.2100",
                "productDescription": "TEST",
                "rate": "0%",
                "uoM": "Numbers, pieces, units",
                "quantity": 1,
                "valueSalesExcludingST": 100,
                "fixedNotifiedValueOrRetailPrice": 100,
                "salesTaxApplicable": 0,
                "salesTaxWithheldAtSource": 0,
                "extraTax": 0,
                "furtherTax": 0,
                "sroScheduleNo": "EIGHTH SCHEDULE Table 1",
                "fedPayable": 0,
                "discount": 0,
                "totalValues": 0,
                "saleType": "Non-Adjustable Supplies",
                "sroItemSerialNo": "81"
            }
        ]
    },
    "SN026": {
        "invoiceType": "Sale Invoice",
        "invoiceDate": "2025-05-16",
        "sellerNTNCNIC": "0000000",
        "sellerBusinessName": "XYZ",
        "sellerProvince": "Sindh",
        "sellerAddress": "Karachi",
        "buyerNTNCNIC": "2046004",
        "buyerBusinessName": "ABC",
        "buyerProvince": "Sindh",
        "buyerAddress": "Karachi",
        "scenarioId": "SN026",
        "invoiceRefNo": "",
        "buyerRegistrationType": "Registered",
        "items": [
            {
                "hsCode": "0101.2100",
                "productDescription": "TEST",
                "rate": "18%",
                "uoM": "Numbers, pieces, units",
                "quantity": 1,
                "totalValues": 590,
                "valueSalesExcludingST": 500,
                "fixedNotifiedValueOrRetailPrice": 500,
                "salesTaxApplicable": 90,
                "salesTaxWithheldAtSource": 0,
                "extraTax": 0,
                "furtherTax": 0,
                "sroScheduleNo": "",
                "fedPayable": 0,
                "discount": 0,
                "saleType": "Goods at standard rate (default)",
                "sroItemSerialNo": ""
            }
        ]
    },
    "SN027": {
        "invoiceType": "Sale Invoice",
        "invoiceDate": "2025-05-10",
        "sellerNTNCNIC": "0000000",
        "sellerBusinessName": "XYZ",
        "sellerProvince": "Sindh",
        "sellerAddress": "Karachi",
        "buyerNTNCNIC": "2046004",
        "buyerBusinessName": "ABC",
        "buyerProvince": "Sindh",
        "buyerAddress": "Karachi",
        "invoiceRefNo": "",
        "scenarioId": "SN027",
        "buyerRegistrationType": "Registered",
        "items": [
            {
                "hsCode": "0101.2100",
                "productDescription": "test",
                "rate": "18%",
                "uoM": "Numbers, pieces, units",
                "quantity": 1,
                "totalValues": 944,
                "valueSalesExcludingST": 800,
                "fixedNotifiedValueOrRetailPrice": 800,
                "salesTaxApplicable": 144,
                "salesTaxWithheldAtSource": 0,
                "extraTax": 0,
                "furtherTax": 0,
                "sroScheduleNo": "",
                "fedPayable": 0,
                "discount": 0,
                "saleType": "3rd Schedule Goods",
                "sroItemSerialNo": ""
            }
        ]
    },
    "SN028": {
        "invoiceType": "Sale Invoice",
        "invoiceDate": "2025-05-16",
        "sellerNTNCNIC": "0000000",
        "sellerBusinessName": "XYZ",
        "sellerProvince": "Sindh",
        "sellerAddress": "Karachi",
        "buyerNTNCNIC": "2046004",
        "buyerBusinessName": "ABC",
        "buyerProvince": "Sindh",
        "buyerAddress": "Karachi",
        "invoiceRefNo": "",
        "scenarioId": "SN028",
        "buyerRegistrationType": "Registered",
        "items": [
            {
                "hsCode": "0101.2100",
                "productDescription": "TEST",
                "rate": "1%",
                "uoM": "Numbers, pieces, units",
                "quantity": 1,
                "totalValues": 101,
                "valueSalesExcludingST": 100,
                "fixedNotifiedValueOrRetailPrice": 100,
                "salesTaxApplicable": 1,
                "salesTaxWithheldAtSource": 0,
                "extraTax": "",
                "furtherTax": 0,
                "sroScheduleNo": "EIGHTH SCHEDULE Table 1",
                "fedPayable": 0,
                "discount": 0,
                "saleType": "Goods at Reduced Rate",
                "sroItemSerialNo": "70"
            }
        ]
    }
};